version: '3'

silent: true

tasks:
  install:
    desc: install dependencies
    cmds: [ task: install-ui ]

  install-ui:
    desc: lint ui
    dir: ui/
    cmds: [ npm ci ]

  world:
    desc: run all validation steps
    cmds:
      - task: assert-validate-preconditions
      - task: lint
      - task: test

  assert-validate-preconditions:
    desc: require validation preconditions
    dir: build/
    cmds: [ ./validate-preconditions.sh ]

  lint:
    desc: lint project
    cmds: [ task: lint-ui ]

  lint-ui:
    desc: lint ui
    dir: ui/
    cmds: [ npm -s run lint ]

  test:
    desc: run tests
    cmds: [ task: test-ui ]

  test-ui:
    desc: run ui tests
    dir: ui/
    cmds: [ npm -s run test ]

  default:
    cmds: [ task: world ]