version: '3'

silent: true

tasks:
  install:
    desc: install dependencies
    cmds: [ task: install-tools, task: install-ui ]

  install-tools:
    desc: install required tools
    cmds:
      - build/run.sh 'install-golangci-lint' tools/ ./install-golangci-lint.sh

  install-ui:
    desc: install ui
    cmds: [ build/run.sh 'install-ui' ui/ npm ci ]

  world:
    desc: run all validation steps
    cmds:
      - task: validate-preconditions
      - task: format
      - task: lint
      - task: test

  validate-preconditions:
    desc: validate preconditions
    cmds: [ build/run.sh 'validate-preconditions' build/ ./validate-preconditions.sh ]

  format:
    desc: format source-code
    cmds: [ task: format-ui ]

  format-ui:
    desc: format ui
    cmds: [ build/run.sh 'format-ui' ui/ npm run format ]

  format-service:
    desc: format service
    cmds: [ build/run.sh 'format-service' service/ go fmt ./... ]

  lint:
    desc: lint project
    cmds: [ task: lint-ui ]

  lint-ui:
    desc: lint ui
    cmds: [ build/run.sh 'lint-ui' ui/ npm run lint ]

  lint-service:
    desc: lint service
    cmds: [ build/run.sh 'lint-service' service/ ../tools/bin/golangci-lint run ]

  test:
    desc: run tests
    cmds: [ task: test-ui, task: test-service ]

  test-ui:
    desc: run ui tests
    dir: ui/
    cmds:
      - task: unit-test-ui
      - task: component-test-ui

  unit-test-ui:
    desc: run ui unit-tests
    cmds: [ build/run.sh 'unit-test-ui' ui/ npm run test ]

  component-test-ui:
    desc: run ui component-tests
    deps: [ start-ui ]
    dir: ui/
    cmds:
      - ../build/run.sh 'component-test-ui' ./ npm run component-test
      - task: stop-ui

  start-ui:
    desc: locally start ui
    deps: [ stop-ui ]
    dir: ui/
    cmds:
      - screen -dmS ui npm run start
      - ./wait-healthy.sh

  stop-ui:
    desc: locally stop ui
    cmds: [ '(! lsof -ti tcp:4200 &> /dev/null) || kill -9 $(lsof -ti tcp:4200) &> /dev/null || true' ]

  test-service:
    desc: run tests for service
    cmds: [ build/run.sh 'test-service' service/ go test ./... ]

  default:
    cmds: [ task: world ]