version: '3'

silent: true

tasks:
  install:
    desc: install dependencies
    cmds: [ task: install-ui ]

  install-ui:
    desc: lint ui
    dir: ui/
    cmds: [ npm ci ]

  world:
    desc: run all validation steps
    cmds:
      - task: assert-validate-preconditions
      - task: format
      - task: lint
      - task: test

  assert-validate-preconditions:
    desc: require validation preconditions
    dir: build/
    cmds: [ ./validate-preconditions.sh ]

  format:
    desc: format source-code
    cmds: [ task: format-ui ]

  format-ui:
    desc: format ui
    dir: ui/
    cmds: [ npm run format ]

  lint:
    desc: lint project
    cmds: [ task: lint-ui ]

  lint-ui:
    desc: lint ui
    dir: ui/
    cmds: [ npm -s run lint ]

  test:
    desc: run tests
    cmds: [ task: test-ui ]

  test-ui:
    desc: run ui tests
    dir: ui/
    cmds:
      - task: unit-test-ui
      - task: component-test-ui

  unit-test-ui:
    desc: run ui unit-tests
    dir: ui/
    cmds: [ npm run test ]

  component-test-ui:
    desc: run ui component-tests
    deps: [ start-ui ]
    dir: ui/
    cmds:
      - npm run component-test
      - task: stop-ui

  start-ui:
    desc: locally start ui
    deps: [ stop-ui ]
    dir: ui/
    cmds:
      - screen -dmS ui npm run start
      - ./wait-healthy.sh

  stop-ui:
    desc: locally stop ui
    cmds: [ '(! lsof -ti tcp:4200 &> /dev/null) || kill -9 $(lsof -ti tcp:4200) &> /dev/null || true' ]

  default:
    cmds: [ task: world ]